#!/bin/bash

_USER_=$( ( awk '/-u / { print $2 }' < $HOME/.config/mosquitto.amqtt.alslug.xyz ; echo user ) | head -1 )
_HOSTNAME_=$( hostname )
_MOSQUITTO_PARAMS_="--host mqtt.alslug.xyz -u $_USER_"

function update {
	TOPIC=computers/$_USER_/$_HOSTNAME_/$1
	NEW=$2
	OLD=$3
	if [ x"$NEW" != x ] ; then
		OLD=$( mosquitto_sub -W 1 -C 1                          $_MOSQUITTO_PARAMS_ --topic $TOPIC	)
		[ x"$NEW" != x"$OLD" ] && echo "$NEW"	| mosquitto_pub	$_MOSQUITTO_PARAMS_ --topic $TOPIC -s --retain
	fi
}

for CMD_A in uname                                              ; do NEW=$( $CMD_A -a)                                                        ; update $CMD_A               "$NEW" ; done
for PARAM in id description release codename                    ; do NEW=$( lsb_release --$PARAM )                                            ; update lsb_release/$PARAM   "$NEW" ; done
for PACKAGE in linux-image-generic $( dpkg linux-image-rpi-\* ) ; do NEW=$( dpkg -l $PACKAGE | awk '/'$PACKAGE'/ { print $3 }'	2>/dev/null ) ; update $PACKAGE             "$NEW" ; done 2>/dev/null 

